[config]
save_dir = "TwoDGridWorld_ESARSA_Control_esp"
exp_file = "experiments/2d-gridworld.jl"
exp_module_name = "TwoDGridWorldExperiment"
exp_func_name = "main_experiment"
arg_iter_type = "iter"

[static_args]

steps = 200000

logger_keys = ["TWODGRIDWORLDERROR", "TWODGRIDWORLDERRORDPI", "ONED_GOAL_VISITATION", "EPISODE_LENGTH", "INTRINSIC_REWARD", "BEHAVIOUR_ACTION_VALUES"]
logger_interval = 100

# Behaviour Items
behaviour_learner = "GPI"
behaviour_update = "TB"
behaviour_reward_projector = "state_agg"

behaviour_opt = "Auto"
exploration_strategy = "epsilon_greedy"
behaviour_trace = "ReplacingTraces"

behaviour_gamma = 0.95
behaviour_lambda = 0.9
behaviour_w_init = 4.0

# Demon Attributes
demon_gamma = 0.95
demon_lambda = 0.9
demon_policy_type = "greedy_to_cumulant"
demon_trace = "AccumulatingTraces"
demon_rep = "ideal"

demon_opt = "Auto"
demon_update = "TB"

# Agent and Logger
horde_type = "regular"
intrinsic_reward = "weight_change"
use_external_reward = true

# Environment Config
cumulant_schedule = "DrifterDistractor"
constant_target= [-10.0,10.0]
distractor = [1.0, 5.0]
drifter = [1.0, 0.1] # drifter is the sqrt(0.01)

env_step_penalty = -0.01


[sweep_args]
seed = "1:10"

alpha_init = [0.1, 0.5, 1.0] # Will be 1/tilings from sweep
eta = "0.1 * 2.0.^(-8:0)"

exploration_param = [0.1]
demon_learner = ["Q", "SR"]

tiling_structure = [[16,2], [8,2], [1, 16]]
start_dist = ["center"]
