[config]
save_dir = "test_InterestTBExperiment2ESARSA"
exp_file = "experiments/tabular_tmaze.jl"
exp_module_name = "TabularTMazeExperiment"
exp_func_name = "main_experiment"
arg_iter_type = "iter"

[static_args]

# steps = 60000
steps = 200
logger_keys = ["TTMAZE_ERROR", "TTMAZE_UNIFORM_ERROR", "TTMAZE_OLD_ERROR", "GOAL_VISITATION", "EPISODE_LENGTH","INTRINSIC_REWARD", "TTMAZE_DIRECT_ERROR"]

# Behaviour Items
# behaviour_eta = 0.2
behaviour_gamma = 0.9
behaviour_learner = "Q"
behaviour_update = "ESARSA"
behaviour_trace = "AccumulatingTraces"
behaviour_opt = "Auto"
behaviour_lambda = 0.9
# behaviour_alpha_init = 0.1
behaviour_w_init = 10

# exploration_param = 0.0
exploration_strategy = "epsilon_greedy"

# Demon Attributes
# demon_alpha_init = 0.1
# demon_eta = 0.5
demon_discounts = 0.9
# demon_learner = "SR"
# demon_update = "TB"
demon_policy_type = "greedy_to_cumulant"
# demon_opt = "Auto"
demon_lambda = 0.9
demon_trace = "AccumulatingTraces"

# Environment Config
constant_target= [-10.0,10.0]
cumulant_schedule = "DrifterDistractor"
distractor = [1.0, 5.0]
drifter = [1.0, 0.1] # drifter is the sqrt(0.01)
exploring_starts=false
env_step_penalty= -0.01


# Agent and Logger
horde_type = "regular"
intrinsic_reward = "weight_change"
# save_dir = "TabularTMazeExperiment"
# seed = 1
use_external_reward = true
logger_interval = 100

[sweep_args]
seed = "1:30"
exploration_param = [0.1]
eta = "5.0 .^ (-3:0)"
demon_update = ["TB", "InterestTB"]
demon_learner = ["Q", "SR"]
demon_opt = ["Auto"]
demon_alpha_init = [0.1, 1.0, 5.0, 10.0]
behaviour_alpha_init = [0.1, 1.0]
