[config]
save_dir = "test_InterestTBExperiment1"
exp_file = "experiments/tabular_tmaze.jl"
exp_module_name = "TabularTMazeExperiment"
exp_func_name = "main_experiment"
arg_iter_type = "iter"

[static_args]

# steps = 2000
steps = 200
logger_keys = ["TTMAZE_ERROR", "TTMAZE_UNIFORM_ERROR", "TTMAZE_OLD_ERROR", "TTMAZE_DIRECT_ERROR"]

# Behaviour Items
behaviour_eta = 0.2
behaviour_gamma = 0.9
behaviour_learner = "Q"
behaviour_update = "TabularRoundRobin"
behaviour_trace = "AccumulatingTraces"
behaviour_opt = "Descent"
behaviour_lambda = 0.9
behaviour_alpha_init = 0.1
# exploration_param = 0.0
exploration_strategy = "epsilon_greedy"

# Demon Attributes
# demon_alpha_init = 1.0
# demon_eta = 0.5
demon_discounts = 0.9
# demon_learner = "SR"
# demon_update = "TB"
demon_policy_type = "greedy_to_cumulant"
# demon_opt = "Descent"
demon_lambda = 0.9
demon_trace = "AccumulatingTraces"
demon_beta_m = 0.9
demon_beta_v = 0.99

# Environment Config
constant_target= 1.0
cumulant_schedule = "DrifterDistractor"
distractor = [1.0, 1.0]
drifter = [1.0, 0.1] # drifter is the sqrt(0.01)
exploring_starts=false

# Agent and Logger100
horde_type = "regular"
intrinsic_reward = "weight_change"
logger_interval = 50
# save_dir = "TabularTMazeExperiment"
# seed = 1
use_external_reward = true

[sweep_args]
seed = "1:30"
demon_alpha_init = [0.1, 1.0, 5.0, 10.0]
demon_eta = [0.03, 0.1, 0.3, 1.0]
demon_opt = ["Auto"]
demon_learner = ["SR", "Q"]
demon_update = ["TB", "InterestTB", "ETB"]
exploration_param = [0.0]

# demon_opt = ["Auto"]
