[config]
save_dir = "TwoDGridWorld_gpi_TB"
exp_file = "experiments/2d-gridworld.jl"
exp_module_name = "TwoDGridWorldExperiment"
exp_func_name = "main_experiment"
arg_iter_type = "iter"

[static_args]

steps = 40000
# steps = 10

logger_keys = ["TWODGRIDWORLDERROR", "TWODGRIDWORLDERRORDPI", "ONED_GOAL_VISITATION", "EPISODE_LENGTH", "INTRINSIC_REWARD", "BEHAVIOUR_ACTION_VALUES"]
logger_interval = 100

# Behaviour Items

behaviour_gamma = 0.9

exploration_strategy = "epsilon_greedy"
behaviour_lambda = 0.9
behaviour_w_init = 4.0
behaviour_trace = "ReplacingTraces"
behaviour_reward_projector = "state_agg"
behaviour_bpd = 5

# Demon Attributes
demon_gamma = 0.95
demon_lambda = 0.9
demon_policy_type = "greedy_to_cumulant"
demon_trace = "AccumulatingTraces"
demon_rep = "ideal"
demon_interest_set = "2dOpenWorld_center"
demon_normalize_interest = true

# Agent and Logger
horde_type = "regular"
intrinsic_reward = "weight_change"
use_external_reward = true
behaviour_opt = "Auto"
demon_opt = "Auto"
behaviour_learner = "GPI"
behaviour_update = "TB"


# Environment Config
cumulant_schedule = "DrifterDistractor"
constant_target= [-10.0,10.0]
distractor = [1.0, 2.236]
drifter = [1.0, 0.01] # drifter is the sqrt(0.01)
env_step_penalty = -0.01


[sweep_args]
seed = "1:1"

alpha_init = [0.1, 0.5, 1.0]
eta = [0.1, 0.5, 1.0]
# emphasis_clip_threshold = [0.1, 1.0, 10.0]

exploration_param = [0.1]
demon_learner = ["SR"]
demon_update = ["TB", "InterestTB"]
tiling_structure = [[16, 2]]
start_dist = ["center"]
