[config]
save_dir = "OneDTMazeQ"
exp_file = "experiments/1d-tmaze.jl"
exp_module_name = "OneDTmazeExperiment"
exp_func_name = "main_experiment"
arg_iter_type = "iter"

[static_args]

steps = 50000

logger_keys = ["ONEDTMAZEERROR", "ONED_GOAL_VISITATION", "EPISODE_LENGTH"]
logger_interval = 100
# Behaviour Items
behaviour_gamma = 0.9
behaviour_learner = "RoundRobin"
behaviour_update = "RoundRobin"
exploration_strategy = "epsilon_greedy"

# Demon Attributes
demon_alpha_init = 1 # Will be 1/tilings from sweep
demon_beta_m = 0.9
demon_beta_v = 0.99
demon_rho = 0.9

demon_discounts = 0.9
demon_policy_type = "greedy_to_cumulant"
demon_lambda = 0.9
demon_trace = "AccumulatingTraces"



# Environment Config
constant_target= 1.0
cumulant = 1.0
distractor = [1.0, 1.0]
drifter = [0.1, 1.0] # drifter is the sqrt(0.01), (std, mean)

exploring_starts="whole"

# Agent and Logger
horde_type = "regular"
intrinsic_reward = "weight_change"

use_external_reward = true
exploration_param = 0.0

[sweep_args]
seed = "1:30"
# runs = "1:2"
cumulant_schedule = ["Constant", "DrifterDistractor"]
demon_eta = "0.1 * 1.5.^(-8:2)"
demon_opt = ["Auto", "Descent", "ADAM", "RMSProp"]

demon_update = ["TB", "ESARSA"]
demon_learner = ["Q"]

num_tiles = [4, 8, 16]
num_tilings = [1, 4, 8]
# behaviour_eta = "2.0 .^ (-1:-1)"


# demon_opt = ["Auto"]
